spring.application.name=neighbourHood
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-young-mouse-a1qzjkq8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6GvlhkwZX5xU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Java Persistence API for you to access database without real SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Supabase Storage 
supabase.endpoint=https://juqebmxjubypqpslvxds.storage.supabase.co
supabase.access-key=a83ea0ce78977d390fa1837a199c44c3
supabase.secret-key=752fe79d86f3e817707c4108e7c6d980879fe31ed7cda86e2834e4213d1bcc9d
supabase.bucket=neighbourHood-photos

spring:
  security:
    user: